Placing check in repo for .git presence
Accenture/adop-pluggable-scm pull request #11
Opened 2017-03-10 15:03 UTC by dsingh07

By default we assume that all git urls in urls.txt have a ".git" at the end, this check will enable urls without .git at the end to work as well.

2017-03-11 12:02 UTC, RobertNorthard requested changes

2017-03-11 12:02 UTC, RobertNorthard commented on src/main/groovy/pluggable/scm/bitbucket/BitbucketSCMProvider.groovy
> +          String repoName = repo.substring(repo.lastIndexOf("/") + 1, repo.length());
I think we need to actually validate the repository URL (repo) here (e.g. is it a valid SSH/HTTPS clone URL).

2017-03-13 22:18 UTC, RobertNorthard approved these changes

2018-05-08 15:38 UTC, RobertNorthard submitted a review, later dismissed
Thanks @dsingh07 this looks good to me.

2018-05-08 15:39 UTC, RobertNorthard commented
@dsingh07 please can you rebase?

2018-05-08 15:54 UTC, dsingh07 commented
@RobertNorthard Done :)

2018-05-08 15:56 UTC, RobertNorthard approved these changes

2018-05-08 15:57 UTC, merged