Added BitbBucket SCM provider
Accenture/adop-pluggable-scm pull request #4
Opened 2017-02-23 09:12 UTC by RobertNorthard

2017-02-23 11:29 UTC, dsingh07 commented
@RobertNorthard Can we squash the commit which says "Removed not working part"?

2017-02-23 11:53 UTC, RobertNorthard commented
@dsingh07 rebased 👍

2017-02-23 16:42 UTC, SachinKSingh28 requested changes

2017-02-23 16:42 UTC, SachinKSingh28 commented on src/main/groovy/pluggable/scm/bitbucket/BitbucketRequestUtil.groovy
> +          repositoryList.add(json.values[i].name)
we should check for the paging in the json response as well.

2017-02-23 16:42 UTC, SachinKSingh28 commented on src/main/groovy/pluggable/scm/bitbucket/BitbucketSCMProvider.groovy
> +          if(this.bitbucketEndpoint != "/"){
should check for a trailing "/" and append if it doesn't exists.

2017-02-23 23:03 UTC, RobertNorthard commented on src/main/groovy/pluggable/scm/bitbucket/BitbucketRequestUtil.groovy
> +          repositoryList.add(json.values[i].name)
Good shout! I've defaulted the limit to 100. We will add this as an issue to support pagination.

2017-02-24 15:40 UTC, RobertNorthard commented on src/main/groovy/pluggable/scm/bitbucket/BitbucketSCMProvider.groovy
> +        def gitDir = "--git-dir=" + tempDir + "/" + repoName + "/.git"
BitBucket password should be ASCII encoded as it's a url. What if someone has an '@' in their password?

2017-02-28 17:04 UTC, dsingh07 reviewed
Looks good @RobertNorthard @SachinKSingh28 

Have tested this one a fresh /C and it works as expected, in conjunction with https://github.com/Accenture/adop-platform-management/pull/30

Once the commits have been squashed, this is ready to be merged in.

2017-03-06 15:41 UTC, dsingh07 commented
LGTM, thanks @RobertNorthard @BuleGeorge @SachinKSingh28 @MarisBahtins @IrmantasM

2017-03-06 15:42 UTC, merged

2017-03-06 16:38 UTC, SachinKSingh28 commented
I think we need to publish the github pages as well.

2017-03-08 11:04 UTC, RobertNorthard commented
Awesome, thanks @SachinKSingh28. I've updated GitHub pages. The latest changes are now being reflected (https://accenture.github.io/adop-pluggable-scm/javadocs/)